# Generated by Django 3.0.3 on 2020-02-19 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_auto_20200207_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='usermonument',
            name='monument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_monument', to='quizz.Monument'),
        ),
        migrations.AlterField(
            model_name='usermonument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_monument', to=settings.AUTH_USER_MODEL),
        ),
    ]
