# Generated by Django 3.0.3 on 2020-03-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_auto_20200316_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monument',
            old_name='name',
            new_name='city',
        ),
    ]
